name: versions

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  resolve-stable-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [15.0.0, 16.0.0, 16.8.10]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: ./
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          resolve-stable: true
      - if: runner.os != 'Windows'
        name: Verify node and npm
        run: |
          . "$NVM_DIR/nvm.sh"
          [[ $(nvm version-remote "${{ matrix.node-version }}") =~ ^v([^.]+) ]]
          __tests__/verify-node.sh "${BASH_REMATCH[1]}"
        shell: bash